import{a as h,S as y,i as c}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function p(s,t){try{const a="https://pixabay.com/api/",i=new URLSearchParams({key:"44082899-a223f277c19d17b254d670762",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}),e=`${a}?${i}`;return(await h.get(e)).data}catch{iziToast.error({position:"topRight",message:"Error"})}}function u(s){return s.map(t=>`<li class="gallery-list"><div class="gallery"><a href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" width="360px" height="100px"></a>
      <ul class="img-cont-list">
      <li class="img-cont-item">Likes<p class="img-cont-descr">${t.likes}</p></li>
      <li class="img-cont-item">Views<p class="img-cont-descr">${t.views}</p></li>
      <li class="img-cont-item">Comments<p class="img-cont-descr">${t.comments}</p></li>
      <li class="img-cont-item">Downloads<p class="img-cont-descr">${t.downloads}</p></li>
      </ul>
      </div>
      </li>`).join("")}function f(){new y(".gallery a",{navText:["&#5176;","&#5171;"],captionsData:"alt",captionDelay:250}).refresh()}const m=document.querySelector(".find-form"),n=document.querySelector(".gallery-container");document.querySelector(".loader");const o=document.querySelector(".btn"),g=document.querySelector("#load");o.addEventListener("click",v);let d=1,L="";m.addEventListener("submit",async s=>{s.preventDefault(),n.innerHTML="";const a=new FormData(m).get("find-text");if(a!==""){n.innerHTML='<div class = "loading">Loading...  <span class="loader"></span></div>';try{const i=await p(a,d);if(i.hits.length===0){c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.innerHTML="";return}const e=u(i.hits);n.innerHTML=e,f()}catch{c.error({position:"topRight",message:"Error"})}finally{s.target.reset(),o.classList.remove("hidden")}}});async function v(){o.classList.add("hidden"),d+=1,g.innerHTML='<div class = "loading">Loading...  <span class="loader"></span></div>';try{const s=await p(L,d);s.hits.length===0&&(o.classList.add("hidden"),c.info({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),g.innerHTML="",o.classList.add("hidden"),o.disable=!0;const t=u(s.hits);n.insertAdjacentHTML("beforeend",t),o.disable=!0,f(),window.scrollBy({top:720,behavior:"smooth"})}catch(s){c.error({position:"topRight",message:s.message})}finally{o.classList.remove("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
