import{a as h,S as L,i as l}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();async function u(i,t){try{const n="https://pixabay.com/api/",a=new URLSearchParams({key:"44082899-a223f277c19d17b254d670762",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}),e=`${n}?${a}`;return(await h.get(e)).data}catch{iziToast.error({position:"topRight",message:"Error"})}}function y(i){return i.map(t=>`<li class="gallery-list"><div class="gallery"><a href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" width="360px" height="100px"></a>
      <ul class="img-cont-list">
      <li class="img-cont-item">Likes<p class="img-cont-descr">${t.likes}</p></li>
      <li class="img-cont-item">Views<p class="img-cont-descr">${t.views}</p></li>
      <li class="img-cont-item">Comments<p class="img-cont-descr">${t.comments}</p></li>
      <li class="img-cont-item">Downloads<p class="img-cont-descr">${t.downloads}</p></li>
      </ul>
      </div>
      </li>`).join("")}function f(){new L(".gallery a",{navText:["&#5176;","&#5171;"],captionsData:"alt",captionDelay:250}).refresh()}const p=document.querySelector(".find-form"),r=document.querySelector(".gallery-container"),o=document.querySelector(".btn"),g=document.querySelector("#load");document.querySelector(".find-btn");let d=1,c="";p.addEventListener("submit",async i=>{if(i.preventDefault(),d=1,r.innerHTML="",c=new FormData(p).get("find-text"),!!c){r.innerHTML='<div class="loader"></div>';try{const t=await u(c,d);if(t.hits.length===0){l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),r.innerHTML="";return}r.innerHTML=y(t.hits),f()}catch{l.error({position:"topRight",message:"Ooops"})}finally{i.target.reset(),o.classList.remove("hidden"),o.style.display="block"}}});o.addEventListener("click",v);async function v(){o.classList.add("hidden"),d+=1,g.innerHTML='<div class="loading">Loading...  <span class="loader"></span></div>';try{const i=await u(c,d);i.hits.length===0?(o.classList.add("hidden"),l.info({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})):(r.insertAdjacentHTML("beforeend",y(i.hits)),f(),window.scrollBy({top:720,behavior:"smooth"}))}catch{l.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),o.style.display="none"}finally{g.innerHTML="",o.classList.remove("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
